/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      keyframes: {
        "slide-in": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "slide-in": "slide-in 0.25s ease-out",
      },
      colors: {
        // Design System: "The Elevated Professional"
        "surface-container-low": "#f2f4f6",
        "secondary": "#515f74",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "surface-dim": "#d8dadc",
        "secondary-fixed-dim": "#b9c7df",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#eeefff",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#6ffbbe",
        "primary": "#004ac6",
        "tertiary-fixed-dim": "#4edea3",
        "inverse-primary": "#b4c5ff",
        "on-secondary-fixed-variant": "#3a485b",
        "on-error": "#ffffff",
        "tertiary-container": "#007d55",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "on-primary-fixed": "#00174b",
        "surface-container-highest": "#e0e3e5",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bdffdb",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface-variant": "#434655",
        "error-container": "#ffdad6",
        "on-secondary-container": "#57657a",
        "secondary-container": "#d5e3fc",
        "secondary-fixed": "#d5e3fc",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "tertiary": "#006242",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "outline": "#737686",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed": "#0d1c2e",
        "background": "#f7f9fb",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-fixed": "#002113",
        "surface-tint": "#0053db",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        // Ambient depth shadows (blue-tinted for premium feel)
        "ambient": "0 32px 64px -12px rgba(0, 74, 198, 0.06)",
        "ambient-md": "0 16px 32px -8px rgba(0, 74, 198, 0.04)",
        "ambient-sm": "0 8px 16px -4px rgba(0, 74, 198, 0.03)",
      },
      backdropBlur: {
        glass: "20px",
      },
    },
  },
  plugins: [],
};
